import type { Question } from './types'

export const ALL_Q: Question[] = [
  { id: 0, topic: "CIS", mark: "2-mark", type: "fill", q: "A Computer Information System collects, processes, stores, and _____ information for decision making.", blanks: ["distributes"], hint: "Think of the last step — getting info out to users." },
  { id: 1, topic: "Software Engineering", mark: "2-mark", type: "fill", q: "Software Engineering applies _____ principles to develop reliable and efficient software economically.", blanks: ["engineering"], hint: "The name itself is the clue." },

  { id: 2, topic: "DFD", mark: "2-mark", type: "mcq", q: "A Data Store in DFD is represented using:", options: ["A circle", "Two parallel lines", "A rectangle", "An arrow"], answer: 1 },

  { id: 3, topic: "Testing", mark: "2-mark", type: "recall", q: "Who performs Alpha Testing?", answers: ["Internal testers"], hint: "Think about who does the first round of testing inside the organization before the client sees it." },

  { id: 4, topic: "Testing", mark: "2-mark", type: "fill", q: "Unit Testing tests individual _____ or components independently and is usually done by developers.", blanks: ["modules"], hint: "Small pieces of code that do one job." },

  { id: 5, topic: "Metrics", mark: "2-mark", type: "tf", q: "A metric is a qualitative measure used to measure software quality, complexity, cost, or productivity.", answer: false, exp: "Metrics are QUANTITATIVE — they use numbers, not descriptive qualities." },

  { id: 6, topic: "Cyclomatic Complexity", mark: "2-mark", type: "fill", q: "Cyclomatic Complexity formula: V(G) = E − N + _____P  (fill the number)", blanks: ["2"], hint: "A small single-digit integer." },

  { id: 7, topic: "Cohesion", mark: "2-mark", type: "recall", q: "Cohesion is the degree of relationship among functions _____ a module.", answers: ["inside"], hint: "Is cohesion about what happens inside a module or between modules?" },

  { id: 8, topic: "Coupling", mark: "2-mark", type: "tf", q: "Coupling is the degree of dependency between modules.", answer: true, exp: "Correct — coupling measures how much modules depend on each other." },

  { id: 9, topic: "Feasibility Study", mark: "2-mark", type: "mcq", q: "Which of these is NOT a type of Feasibility Study?", options: ["Technical", "Operational", "Algorithmic", "Schedule"], answer: 2 },

  { id: 10, topic: "SRS", mark: "2-mark", type: "fill", q: "SRS stands for Software _____ Specification.", blanks: ["Requirement"], hint: "What does an SRS document?" },

  { id: 11, topic: "Brainstorming", mark: "2-mark", type: "tf", q: "Brainstorming is a one-on-one interview technique used for requirement gathering.", answer: false, exp: "Brainstorming is a GROUP discussion technique, not one-on-one." },

  { id: 12, topic: "Waterfall Model", mark: "2-mark", type: "recall", q: "In the Waterfall Model, a new phase begins only after what condition is met?", answers: ["The previous phase is complete", "Previous phase is complete", "Previous phase completed"], hint: "Think about the sequential nature of Waterfall." },

  { id: 13, topic: "Verification", mark: "2-mark", type: "recall", q: "Verification checks whether the software is built _____.", answers: ["correctly"], hint: "Is it about building the product right, or building the right product?" },

  { id: 14, topic: "Validation", mark: "2-mark", type: "tf", q: "Validation uses code execution and testing (dynamic testing).", answer: true, exp: "Correct — Validation is dynamic: it runs the code to check the right product is built." },

  { id: 15, topic: "BVA", mark: "2-mark", type: "recall", q: "List the Boundary Value Analysis test values for input range 18–30.", answers: ["17, 18, 19, 29, 30, 31", "17,18,19,29,30,31", "17 18 19 29 30 31"], hint: "Test at and just outside the lower and upper boundaries." },

  { id: 16, topic: "Functional Requirements", mark: "2-mark", type: "tf", q: "Functional requirements describe WHAT a system should do, such as a login feature.", answer: true, exp: "Correct — functional requirements describe system features and behaviors." },

  { id: 17, topic: "Non-Functional", mark: "2-mark", type: "recall", q: "Name one example of a Non-Functional Requirement.", answers: ["System reliability", "Reliability", "Performance", "Security", "Usability", "Scalability", "Maintainability", "Availability"], hint: "Think about qualities of the system, not specific features." },

  { id: 18, topic: "COCOMO", mark: "2-mark", type: "fill", q: "COCOMO is a software cost estimation model developed by Barry _____.", blanks: ["Boehm"], hint: "Rhymes with 'poem'." },

  { id: 19, topic: "Verification vs Validation", mark: "5-mark", type: "match", q: "Match each activity to Verification or Validation:", pairs: [["Reviews & Inspections", "Verification"], ["Testing", "Validation"], ["Static testing", "Verification"], ["Dynamic testing", "Validation"]] },

  { id: 20, topic: "Waterfall Model", mark: "5-mark", type: "explain", q: "Explain a key disadvantage of the Waterfall Model.", keyTerms: ["changing requirements", "inflexible"], answer: "Difficult to handle changing requirements since each phase must be completed before the next begins, making late changes very costly.", hint: "Think about what happens when the client requests changes after a phase is signed off." },

  { id: 21, topic: "Feasibility Study", mark: "5-mark", type: "recall", q: "Which type of feasibility study checks if the project can be done with available technology?", answers: ["Technical"], hint: "This type of feasibility focuses on tools, hardware, and technical expertise." },

  { id: 22, topic: "DFD Components", mark: "5-mark", type: "match", q: "Match DFD symbols to their meanings:", pairs: [["Rectangle", "External Entity"], ["Circle", "Process"], ["Open Rectangle", "Data Store"], ["Arrow", "Data Flow"]] },

  { id: 23, topic: "Cyclomatic Complexity", mark: "5-mark", type: "fill", q: "In V(G) = E − N + 2P: E = edges, N = nodes, P = _____ components.", blanks: ["connected"], hint: "How are the parts of the graph related to each other?" },

  { id: 24, topic: "Coupling Types", mark: "5-mark", type: "recall", q: "Which coupling type is the WORST (highest dependency)?", answers: ["Content coupling"], hint: "Think about the most invasive kind of coupling where one module modifies data inside another." },

  { id: 25, topic: "Coupling Types", mark: "5-mark", type: "recall", q: "Which coupling type is the BEST (lowest dependency)?", answers: ["Data coupling"], hint: "Think about the least dependent form where only simple data is passed." },

  { id: 26, topic: "Cohesion Types", mark: "5-mark", type: "recall", q: "Which cohesion type is the BEST (most desirable)?", answers: ["Functional"], hint: "Think about which type means each element serves a single well-defined purpose." },

  { id: 27, topic: "Cohesion Types", mark: "5-mark", type: "recall", q: "Which cohesion type is the WORST (least desirable)?", answers: ["Coincidental"], hint: "Think about which type means elements are grouped together randomly with no meaningful relationship." },

  { id: 28, topic: "BVA", mark: "5-mark", type: "tf", q: "In BVA for range 18–30, the value 20 is a boundary test value.", answer: false, exp: "No — BVA tests: 17, 18, 19 (near min) and 29, 30, 31 (near max). 20 is not a boundary." },

  { id: 29, topic: "Failure Occurrence", mark: "5-mark", type: "mcq", q: "The Bathtub Curve in reliability shows:", options: ["Constant failure rate throughout", "High early failures, then stable, then wear-out", "Only increasing failures", "Only decreasing failures"], answer: 1 },

  { id: 30, topic: "Iterative vs RAD", mark: "15-mark", type: "tf", q: "The RAD Model uses prototypes and has HIGH user involvement compared to the Iterative Model.", answer: true, exp: "Correct — RAD is prototype-based with high user involvement, while Iterative has less user involvement and more planning." },

  { id: 31, topic: "Iterative vs RAD", mark: "15-mark", type: "explain", q: "Explain why the RAD Model is more suitable than the Iterative Model for small projects with fast delivery requirements.", keyTerms: ["prototypes", "user involvement"], answer: "RAD Model uses prototypes with high user involvement, enabling faster feedback and quicker delivery for small projects.", hint: "Think about what makes RAD different — prototypes and how closely users are involved." },

  { id: 32, topic: "Requirement Elicitation", mark: "15-mark", type: "fill", q: "FAST stands for Facilitated Application _____ Technique.", blanks: ["Specification"], hint: "What does FAST produce as output?" },

  { id: 33, topic: "Requirement Elicitation", mark: "15-mark", type: "mcq", q: "QFD in requirement elicitation stands for:", options: ["Quality Function Deployment", "Quick Feature Design", "Quantified Functional Data", "Query Form Design"], answer: 0 },

  { id: 34, topic: "Design Strategies", mark: "15-mark", type: "explain", q: "Explain what Top-down design means and how it works.", keyTerms: ["main system", "subsystems", "break down"], answer: "Top-down design starts from the main system and breaks it into smaller subsystems, continuing until the lowest level of detail is reached.", hint: "Think about the direction — do you start with the big picture or the small pieces?" },

  { id: 35, topic: "Design Strategies", mark: "15-mark", type: "reconstruct", q: "Reconstruct the definition: A Hybrid Design Strategy combines _____ and _____.", blanks: ["Top-down", "Bottom-up"], hint: "Think about the two opposite design approaches." },

  { id: 36, topic: "Path Testing", mark: "15-mark", type: "fill", q: "Path Testing is based on drawing a _____ Flow Graph to find all independent paths.", blanks: ["Control"], hint: "It's about how control moves through the program." },

  { id: 37, topic: "Data Flow Testing", mark: "15-mark", type: "reconstruct", q: "Data Flow Testing primarily detects _____ and _____ variables.", blanks: ["Undefined", "unused"], hint: "Think about variables that are not properly initialized or never used." },

  { id: 38, topic: "Testing Levels", mark: "15-mark", type: "match", q: "Order these testing levels from lowest to highest:", pairs: [["1st level", "Unit Testing"], ["2nd level", "Integration Testing"], ["3rd level", "System Testing"], ["4th level", "Acceptance Testing"]] },

  { id: 39, topic: "Testing Levels", mark: "15-mark", type: "mcq", q: "Which testing level checks interaction between modules?", options: ["Unit Testing", "Integration Testing", "System Testing", "Acceptance Testing"], answer: 1 },

  { id: 40, topic: "Requirements Abstraction", mark: "2-mark", type: "abstract", examples: ["The system must log in within 2 seconds", "The system must support 1000 concurrent users", "The system must have 99.9% uptime"], q: "What general category do all three requirements above belong to?", answers: ["Non-functional requirements", "Non-functional", "Non functional requirements", "Non functional"], hint: "Are these describing specific features or qualities of the system?", exp: "All three are non-functional requirements — they describe system qualities (performance, scalability, reliability), not specific features or behaviors." },

  { id: 41, topic: "Verification vs Validation", mark: "2-mark", type: "abstract", examples: ["A team reviews code against the specification (no code execution)", "A team tests the final product with real users", "A team walks through a design document to find errors"], q: "Which two general verification/validation categories do these examples belong to?", answers: ["Verification and validation", "Verification & validation", "Static and dynamic", "Static & dynamic"], hint: "Look at which examples involve running code and which don't.", exp: "Reviews/walkthroughs = Verification (static, no execution). User testing = Validation (dynamic, real execution)." },

  { id: 42, topic: "Cohesion vs Coupling", mark: "5-mark", type: "abstract", examples: ["Module A has functions that all calculate tax-related values", "Module B reads a config file, sends an email, and formats a report", "Module C has one function: 'calculateTotal(items)'"], q: "What software design principle do these examples illustrate?", answers: ["Cohesion", "Module cohesion", "Functional cohesion", "Cohesion principle"], hint: "It measures how focused the functions inside a single module are.", exp: "These illustrate the Cohesion principle: A = functional (high), B = coincidental (low), C = functional (high). Cohesion measures how related the elements inside a module are." },

  { id: 43, topic: "Process Models", mark: "5-mark", type: "abstract", examples: ["A team completes all requirements before starting design, and all design before coding", "A team builds a small prototype, shows the client, then refines it in cycles", "A team divides the project into small increments, delivering working features each week"], q: "What general software process categories do these represent?", answers: ["Waterfall, RAD, and Iterative", "Waterfall RAD Iterative", "Traditional, prototyping, incremental", "Waterfall, prototyping, iterative"], hint: "Think about the three main SDLC model categories distinguished by how they handle phases.", exp: "These map to: 1 = Waterfall (sequential phases), 2 = RAD (prototype-driven), 3 = Iterative (incremental delivery). Each model handles feedback and change differently." },

  { id: 44, topic: "Requirement Elicitation", mark: "5-mark", type: "abstract", examples: ["A facilitator leads a structured group session to define requirements", "An analyst interviews stakeholders one-on-one to gather needs", "A team brainstorms ideas in a free-form group discussion"], q: "What general requirement gathering category do these belong to?", answers: ["Requirement elicitation techniques", "Elicitation techniques", "Requirements elicitation", "Elicitation"], hint: "This is the general name for the process of gathering requirements from stakeholders.", exp: "These are all Requirement Elicitation techniques. 1 = FAST (Facilitated Application Specification Technique), 2 = Interviews, 3 = Brainstorming. Each is a different approach to the same goal." },

  { id: 45, topic: "Testing Abstraction", mark: "15-mark", type: "abstract", examples: ["A developer tests a single function with different inputs", "A QA team tests whether integrated modules work together", "A client runs acceptance tests to verify the system meets business needs"], q: "What testing hierarchy do these examples represent?", answers: ["Testing levels", "Levels of testing", "Unit, Integration, and Acceptance testing", "Unit Integration Acceptance"], hint: "Think about the order of testing from smallest scope to largest.", exp: "These are Testing Levels: Unit Testing (smallest scope, single function), Integration Testing (module interaction), Acceptance Testing (full system against business needs)." },

  { id: 46, topic: "Design Abstraction", mark: "15-mark", type: "abstract", examples: ["A system architect first identifies the main system, then breaks it into subsystems, and finally into individual modules", "A developer starts by designing low-level data structures and builds upward to the full system"], q: "What two design strategies do these examples demonstrate?", answers: ["Top-down and bottom-up", "Top-down & bottom-up", "Top down and bottom up"], hint: "The direction of decomposition is opposite in each case.", exp: "Example 1 = Top-down design (big picture first, then decompose). Example 2 = Bottom-up design (small components first, then compose). A Hybrid approach combines both." },

  { id: 47, topic: "Transfer: Waterfall", mark: "2-mark", type: "transfer", q: "The Waterfall Model requires completing each phase (requirements → design → implementation → testing) before moving to the next. Now think about baking a complex layered cake — you must prepare ingredients, bake layers, prepare frosting, assemble, then decorate. Describe how the Waterfall Model's sequential risk applies to baking. What happens if you discover a problem after a phase is 'complete'?", keyTerms: ["phase", "rework", "start over", "later"], answer: "In both Waterfall and baking, each phase depends on the previous one being correct. If the cake layers are burnt (design flaw), you discover it only during assembly (late phase) — just like finding a requirements error during testing. Rework means going back multiple phases, which is costly and time-consuming. The sequential model assumes perfect foresight, which rarely exists in complex tasks.", hint: "Think about discovering a mistake in a later phase that forces going back." },

  { id: 48, topic: "Transfer: Coupling", mark: "5-mark", type: "transfer", q: "Coupling measures dependency between modules (tight = bad, loose = good). Apply this concept to organizing departments in a company. Describe what 'tight coupling' between Sales and Engineering looks like, and what 'loose coupling' would mean. Which is better and why?", keyTerms: ["dependency", "independent", "communication", "change"], answer: "Tight coupling: Sales promises features without consulting Engineering, Engineering must drop everything to fulfill promises — any change in one forces change in the other. Loose coupling: Sales communicates through a formal process, Engineering publishes capacity roadmaps, both teams operate independently with minimal coordination. Loose coupling is better because changes in one team don't cascade to the other.", hint: "Think about what happens when one department changes its process." },

  { id: 49, topic: "Transfer: Cohesion", mark: "5-mark", type: "transfer", q: "Cohesion measures how focused the elements inside a module are (high = good, low = bad). Apply this to organizing a toolbox. Describe a 'high-cohesion' tool drawer vs a 'low-cohesion' tool drawer. Which makes you more productive and why?", keyTerms: ["related", "purpose", "search", "grouped"], answer: "High-cohesion drawer: all screwdrivers together, all wrenches together, all pliers together — tools grouped by purpose, easy to find what you need. Low-cohesion drawer: random mix of screwdrivers, nails, tape, bolts, and a hammer — you waste time searching, unrelated items crowd each other. High cohesion makes you productive because related tools are together, reducing cognitive load.", hint: "Compare a neatly organized drawer to a junk drawer." },

  { id: 50, topic: "Transfer: Verif vs Valid", mark: "5-mark", type: "transfer", q: "Verification = 'built it right' (static checks), Validation = 'built the right thing' (dynamic testing). Invent a cooking analogy that clearly distinguishes these two concepts. Describe one activity that is Verification-like and one that is Validation-like in the kitchen.", keyTerms: ["recipe", "taste", "check", "right"], answer: "Verification in cooking: checking the recipe steps, measuring ingredients precisely, making sure the oven is at the right temperature — you're checking you followed the process correctly (built it right). Validation: tasting the dish at the end to see if it actually tastes good (built the right thing). You can follow every step perfectly and still produce something that tastes bad — just like passing all verification but failing validation.", hint: "One is about following instructions, the other about checking the result." },

  { id: 51, topic: "Transfer: Testing Levels", mark: "15-mark", type: "transfer", q: "Software testing has levels: Unit (single component) → Integration (interaction) → System (full product) → Acceptance (customer needs). Apply this level-based testing approach to quality control in a car factory. What does each level check, and why is it important to test at all levels instead of just the final one?", keyTerms: ["part", "assembly", "test drive", "customer", "early"], answer: "Unit: test each car part individually (engine, brakes, alternator). Integration: test that parts work together (engine connects to transmission). System: full test drive of the assembled car. Acceptance: customer test drive to verify needs met. Testing only the final car means discovering a faulty alternator too late — testing early (unit level) catches defects when they're cheapest to fix.", hint: "Think about testing a single spark plug vs test driving the whole car." },

  { id: 52, topic: "Transfer: Top-down vs Bottom-up", mark: "15-mark", type: "transfer", q: "Top-down design starts with the big picture and decomposes. Bottom-up design starts with small components and composes. Describe a non-software analogy — from house construction, writing, or music — that illustrates both approaches. Which approach works better for which situation?", keyTerms: ["outline", "details", "foundation", "overall"], answer: "Writing an essay: Top-down = start with an outline (introduction, body, conclusion), then fill in details for each section. Bottom-up = write individual paragraphs first, then arrange them into a coherent essay. Top-down works when you have a clear vision (you know the overall structure). Bottom-up works when you're exploring ideas and discovering the structure as you go. In house construction, top-down is blueprint-first, bottom-up is building rooms and connecting them later.", hint: "Think about writing an outline vs improvising." },

  { id: 53, topic: "Analogy: SRS", mark: "2-mark", type: "analogy", q: "An SRS (Software Requirements Specification) is a detailed document describing what a system must do, serving as a contract between client and developers. Compare this to a real-world document or system outside software — what works similarly and why?", answer: "Like a construction blueprint: it specifies exactly what will be built before construction starts, serves as the contract between architect and builder, and prevents disputes about what was promised. Both require precision because changes during construction/development are expensive." },

  { id: 54, topic: "Analogy: DFD", mark: "2-mark", type: "analogy", q: "A Data Flow Diagram (DFD) shows how data moves through a system — processes transform data, data stores hold it, external entities source/sink it. Describe a real-world system outside computing that operates like a DFD. What are its processes, stores, and flows?", answer: "Like a city's postal system: Processes = sorting offices (transform incoming mail to outgoing), Data stores = post office boxes / warehouses (hold mail temporarily), External entities = senders and recipients (outside the system), Data flows = mail trucks moving between offices (carry letters between nodes)." },

  { id: 55, topic: "Analogy: BVA", mark: "5-mark", type: "analogy", q: "Boundary Value Analysis tests values at the edges of input ranges because most errors occur at boundaries, not in the middle. Find a real-world quality-check analogy outside software that uses the same boundary-focused principle. Why does this pattern recur across domains?", answer: "Like quality control in manufacturing: you test the ends of a tolerance range (e.g., check bolts at the minimum and maximum diameter, not the middle) because manufacturing errors cluster at tolerance boundaries. The principle recurs because systems — whether software or physical — tend to fail at transition points, not in stable middle ranges." },

  { id: 56, topic: "Analogy: Cohesion", mark: "5-mark", type: "analogy", q: "High cohesion means elements inside a module serve a single, well-defined purpose (good). Low cohesion means unrelated elements are grouped together (bad). Find a real-world non-software system where this principle naturally appears — a well-organized vs poorly-organized system. What makes high cohesion valuable there?", answer: "Like a hospital emergency room: High cohesion = triage (all triage together), treatment rooms (all treatment together), radiology (all X-rays together) — each area has a clear purpose, staff stay in their expertise zone. Low cohesion = mixed-use rooms where triage, treatment, and X-rays happen in the same space — chaos, cross-contamination, staff wasting time switching roles. High cohesion makes each unit efficient and focused." },
]
